package vu.lt.fishing.myBatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.fishing.myBatis.model.Fish;

@Mapper
public interface FishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FISH
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FISH
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    int insert(Fish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FISH
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    Fish selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FISH
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    List<Fish> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FISH
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    int updateByPrimaryKey(Fish record);

    List<Fish> selectFishForLake(Integer id);
}