package vu.lt.fishing.myBatis.model;

public class FishingRods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FISHING_RODS.ID
     *
     * @mbg.generated Wed Apr 14 17:16:22 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FISHING_RODS.NAME
     *
     * @mbg.generated Wed Apr 14 17:16:22 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FISHING_RODS.PRICE
     *
     * @mbg.generated Wed Apr 14 17:16:22 EEST 2021
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FISHING_RODS.ID
     *
     * @return the value of PUBLIC.FISHING_RODS.ID
     *
     * @mbg.generated Wed Apr 14 17:16:22 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FISHING_RODS.ID
     *
     * @param id the value for PUBLIC.FISHING_RODS.ID
     *
     * @mbg.generated Wed Apr 14 17:16:22 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FISHING_RODS.NAME
     *
     * @return the value of PUBLIC.FISHING_RODS.NAME
     *
     * @mbg.generated Wed Apr 14 17:16:22 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FISHING_RODS.NAME
     *
     * @param name the value for PUBLIC.FISHING_RODS.NAME
     *
     * @mbg.generated Wed Apr 14 17:16:22 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FISHING_RODS.PRICE
     *
     * @return the value of PUBLIC.FISHING_RODS.PRICE
     *
     * @mbg.generated Wed Apr 14 17:16:22 EEST 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FISHING_RODS.PRICE
     *
     * @param price the value for PUBLIC.FISHING_RODS.PRICE
     *
     * @mbg.generated Wed Apr 14 17:16:22 EEST 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}