package vu.lt.fishing.myBatis.model;

public class Fish {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FISH.ID
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FISH.LENGTH
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    private Double length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FISH.SIZE
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    private Double size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FISH.NAME
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FISH.LAKE_ID
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    private Integer lakeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FISH.ID
     *
     * @return the value of PUBLIC.FISH.ID
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FISH.ID
     *
     * @param id the value for PUBLIC.FISH.ID
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FISH.LENGTH
     *
     * @return the value of PUBLIC.FISH.LENGTH
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public Double getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FISH.LENGTH
     *
     * @param length the value for PUBLIC.FISH.LENGTH
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public void setLength(Double length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FISH.SIZE
     *
     * @return the value of PUBLIC.FISH.SIZE
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public Double getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FISH.SIZE
     *
     * @param size the value for PUBLIC.FISH.SIZE
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public void setSize(Double size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FISH.NAME
     *
     * @return the value of PUBLIC.FISH.NAME
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FISH.NAME
     *
     * @param name the value for PUBLIC.FISH.NAME
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FISH.LAKE_ID
     *
     * @return the value of PUBLIC.FISH.LAKE_ID
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public Integer getLakeId() {
        return lakeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FISH.LAKE_ID
     *
     * @param lakeId the value for PUBLIC.FISH.LAKE_ID
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public void setLakeId(Integer lakeId) {
        this.lakeId = lakeId;
    }
}