package vu.lt.fishing.myBatis.model;

public class Lake {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LAKE.ID
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LAKE.NAME
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LAKE.SIZE
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    private Double size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LAKE.ID
     *
     * @return the value of PUBLIC.LAKE.ID
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LAKE.ID
     *
     * @param id the value for PUBLIC.LAKE.ID
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LAKE.NAME
     *
     * @return the value of PUBLIC.LAKE.NAME
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LAKE.NAME
     *
     * @param name the value for PUBLIC.LAKE.NAME
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LAKE.SIZE
     *
     * @return the value of PUBLIC.LAKE.SIZE
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public Double getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LAKE.SIZE
     *
     * @param size the value for PUBLIC.LAKE.SIZE
     *
     * @mbg.generated Wed Apr 14 13:22:25 EEST 2021
     */
    public void setSize(Double size) {
        this.size = size;
    }
}